### ISSUE TITLE
Crashing when trying to import lyrics? (On Windows 10)

### ISSUE THREAD

**Issue by ButterKing-28** [shensquared/lyricstamp#1]
I have all the requirements. does this work on Windows 10?

**Comment by ButterKing-28** [comment]
I ran it in command prompt (becasue I didn't relise that's how you do it lol) and got this output:
`pygame 2.6.0 (SDL 2.28.4, Python 3.12.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:\Users\******\Downloads\lyricstamp-main\lyricstamp-main\lyricstamp.py", line 9, in <module>
    from phonetics import add_phonetics
  File "C:\Users\******\Downloads\lyricstamp-main\lyricstamp-main\phonetics.py", line 3, in <module>
    from pyjyutping import jyutping
ModuleNotFoundError: No module named 'pyjyutping'
`

**Comment by ButterKing-28** [comment]
After I ran it in command prompt (because I finally realized that's what you were supposed to do lol) I got this error:
```
pygame 2.6.0 (SDL 2.28.4, Python 3.12.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:\Users\******\Downloads\lyricstamp-main\lyricstamp-main\lyricstamp.py", line 9, in <module>
    from phonetics import add_phonetics
  File "C:\Users\******\Downloads\lyricstamp-main\lyricstamp-main\phonetics.py", line 3, in <module>
    from pyjyutping import jyutping
  File "C:\Users\******\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyjyutping\jyutping.py", line 1, in <module>
    from pyjyutping import dictionaries as dicts
  File "C:\Users\******\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyjyutping\dictionaries.py", line 2, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by ButterKing-28** [comment]
I found that you had to do `pip install setuptools` from [this GitHub "issue" for another python program](https://github.com/ManimCommunity/manim/issues/3585) (idk what it is just fond it randomly so sorry if its something bad lol)

Thank you for making this awsome program! <3

**Comment by ButterKing-28** [comment]
Now it runs but when i do any of the ways to import it crashes and gives me an error, this is the error when I try to drag and drop a file, and press the error key and hit enter:

```
pygame 2.6.0 (SDL 2.28.4, Python 3.12.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:\Users\~~~~~\Downloads\lyricstamp-main\lyricstamp-main\lyricstamp.py", line 225, in <module>
    main()
  File "C:\Users\~~~~\Downloads\lyricstamp-main\lyricstamp-main\lyricstamp.py", line 159, in main
    out_name, lines, secs, stamps, screen = get_song_info(lines)
                                            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\~~~~\Downloads\lyricstamp-main\lyricstamp-main\lyricstamp.py", line 44, in get_song_info
    title, artist = player_control.now_playing()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\~~~~Downloads\lyricstamp-main\lyricstamp-main\player_control.py", line 24, in now_playing
    title = execute(titlescript)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\~~~\Downloads\lyricstamp-main\lyricstamp-main\player_control.py", line 6, in execute
    proc = Popen(['osascript', '-'], stdin=PIPE, stdout=PIPE,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\~~~\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\~~~\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified


```

**Comment by shensquared** [comment]
Hi. Sorry about the hiatus.

This is a python compatibility issue -- many dependencies are years old; there's likely broken changes from upstream. For now, can confirm that `python 3.10` virtual env works.

**Comment by shensquared** [comment]
Hi. FYI: The old genius/hard-coded phonetics version is archived on the `legacy-pygame` branch. 

The `main` branch will be AI-assisted with web UI; it should be compatible with newer python compilers (e.g. 3.13).
